Repository mesg-foundation/cli, pull requests merged in 2019-09, with the labels that each got.

#141 Force a configuration to be set for services
  src/utils/compiler.ts
Labels: bug

#147 Update to mesg-js@4.3.0-beta.3
  package-lock.json
  package.json
Labels: dependencies

#142 Process compiler
  README.md
  package.json
  src/commands/process/compile.ts
  src/commands/process/create.ts
  src/commands/process/delete.ts
  src/commands/process/detail.ts
  src/commands/process/list.ts
  src/commands/workflow/create.ts
  src/commands/workflow/detail.ts
  src/commands/workflow/list.ts
  src/utils/compiler.ts
Labels: enhancement

#143 Env support for instance in process compilation
  src/commands/process/compile.ts
Labels: dependencies, enhancement

#148 Fix logs command
  src/commands/service/logs.ts
Labels: bug

#149 Update process compiler
  package-lock.json
  package.json
  src/utils/compiler.ts
Labels: enhancement

#150 add env support for processes
  src/commands/process/compile.ts
  src/utils/compiler.ts
Labels: enhancement

#153 Add support for constants
  package-lock.json
  package.json
  src/utils/compiler.ts
Labels: enhancement

#160 Make deployment from remote deterministic
  src/utils/deployer.ts
Labels: enhancement

#161 Add key to process:list
  src/commands/process/list.ts
Labels: enhancement

#162 Use minor version of the Engine
  package.json
  src/commands/daemon/start.ts
  src/docker-command.ts
  src/version.ts
Labels: enhancement

#154 Add process log command
  README.md
  src/commands/process/logs.ts
Labels: enhancement

#155 Add process dev command
  README.md
  src/commands/process/dev.ts
Labels: enhancement

#165 Fix issue with zero data
  src/commands/service/execute.ts
Labels: bug

#182 Feature/update packages
  package-lock.json
  package.json
  src/utils/compiler.ts
Labels: dependencies

#197 Remove core api and commands relaying on it
  src/account-command.ts
  src/commands/account/create.ts
  src/commands/account/delete.ts
  src/commands/account/export.ts
  src/commands/account/import-private-key.ts
  src/commands/account/import.ts
  src/commands/account/list.ts
  src/commands/exp/account/create.ts
  src/commands/exp/account/delete.ts
  src/commands/exp/account/list.ts
  src/commands/marketplace/create-offer.ts
  src/commands/marketplace/publish.ts
  src/commands/marketplace/purchase.ts
  src/commands/service/compile.ts
  src/marketplace-command.ts
  src/root-command.ts
Labels: enhancement

#198 Update description of service path
  src/commands/service/compile.ts
  src/commands/service/dev.ts
Labels: enhancement

#184 Remove useless account flag in account:XXX commands
  package.json
  src/commands/account/create.ts
  src/commands/account/delete.ts
  src/credential-command.ts
Labels: ux
